- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is started and enabled
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Open firewall ports
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_ports }}"

- name: Allow firewall services
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewalld_services }}"

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded