---
- name: Ensure EPEL and other dependencies are installed
  ansible.builtin.dnf:
    name:
      - epel-release
      - wget 
      - curl
      - httpd
      - mariadb
      - mariadb-server
    state: present

- name: Exclude Zabbix packages from EPEL
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/epel.repo
    regexp: '^excludepkgs='
    line: 'excludepkgs=zabbix*'
    insertafter: '^\[epel\]'
    create: yes

- name: Add Zabbix repository and clean cache
  block:
    - name: Add Zabbix 6.0 repository for RHEL 9
      ansible.builtin.rpm_key:
        state: present
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-08EFA7DD

    - name: Install Zabbix repository
      ansible.builtin.dnf:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-latest-6.0.el9.noarch.rpm
        state: present

    - name: Clean all DNF cache
      ansible.builtin.command: dnf clean all

- name: Install Zabbix server, web frontend, and agent
  ansible.builtin.dnf:
    name: 
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent
    state: present

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes
  
- name: Configure Zabbix database
  block:
    - name: Create Zabbix database
      ansible.builtin.mysql_db:
        name: zabbix
        state: present
        login_user: root

    - name: Create Zabbix database user
      ansible.builtin.mysql_user:
        name: zabbix
        password: password
        priv: 'zabbix.*:ALL'
        host: localhost
        state: present
        login_user: root

    - name: Set global log_bin_trust_function-creators
      ansible.builtin.mysql_variables:
        login_user: root
        variable: log_bin_trust_function_creators
        value: '1'

    - name: Import initial Zabbix schema and data (idempotent)
      ansible.builtin.shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | \
        mysql --default-character-set=utf8mb4 -uzabbix -p'password' zabbix
        touch /var/lib/mysql/.zabbix_schema_imported
      args:
        executable: /bin/bash
        creates: /var/lib/mysql/.zabbix_schema_imported

    - name: Disable log_bin_trust_function_creators
      ansible.builtin.mysql_variables:
        login_user: root
        variable: log_bin_trust_function_creators
        value: '0'

- name: Configure Zabbix database server settings
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^#?DBPassword='
    line: 'DBPassword=password'
    insertafter: '^# DBName='
    create: no  

- name: Ensure Zabbix server and agent are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - zabbix-server
    - zabbix-agent
    - httpd
    - php-fpm