- name: Ensure WinSCP is enabled for file transfers
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check if WinSCP is installed
      win_shell: |
        if (Get-Command winscp) {
          Write-Host "WinSCP is installed."
        } else {
          Write-Host "WinSCP is not installed."
          exit 1
        }
      register: winscp_check
      ignore_errors: true # Continue even if WinSCP is not found
    
    - name: Fail if WinSCP is not installed
      fail:
        msg: "WinSCP is not installed on the target machine. Please install WinSCP."
      when: winscp_check.rc != 0

    - name: Ensure WinSCP COM interface is enabled
      win_shell: |
        try {
          $winscp = New-Object -ComObject WinSCP.Session
          Write-Host "WinSCP COM interface is available."
        } catch {
          Write-Host "WinSCP COM interface is not available. Please ensure WinSCP COM interface is enabled."
          exit 1
        }
      register: winscp_com_check
      ignore_errors: true

    - name: Fail if WinSCP COM interface is not available
      fail:
        msg: "WinSCP COM interface is not available. Ensure WinSCP COM interface is enabled."
      when: winscp_com_check.rc != 0

    - name: Ensure WinSCP path is in the PATH environment variable
      win_shell: |
        $winscpPath = (Get-Command winscp).Path
        $envPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
        if ($envPath -notcontains $winscpPath) {
          Write-Host "WinSCP path is not in the PATH environment variable. Adding it."
          [Environment]::SetEnvironmentVariable("Path", "$envPath;$winscpPath", "Machine")
          Write-Host "WinSCP path added to the PATH environment variable."
        } else {
          Write-Host "WinSCP path is in the PATH environment variable."
        }
      register: winscp_path_check

    - name: Inform of WinSCP path being added to the path.
      debug:
        msg: "WinSCP path has been added to the path variable. Please reboot the target machine for the change to take effect"
      when: "'Adding it.' in winscp_path_check.stdout"