---
- name: Ensure Temp directory exists on target
  ansible.windows.win_file:
    path: "{{ temp_directory }}"
    state: directory

- name: Copy PowerShell scripts to target machine
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ temp_directory }}\\{{ item | basename }}"
  loop:
    - auto_logout_rdp_gpo.ps1
    - remove_power_buttons_gpo.ps1

- name: Execute Remove Power Buttons GPO script
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File "{{ temp_directory }}\remove_power_buttons_gpo.ps1"
  args:
    executable: powershell.exe

- name: Execute Auto Logout RDP GPO script
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File "{{ temp_directory }}\auto_logout_rdp_gpo.ps1"
  args:
    executable: powershell.exe

- name: Link GPOs to domain root
  ansible.windows.win_shell: |
    New-GPLink -Name '{{ item }}' -Target '{{ domain_dn }}' -LinkEnabled Yes -Enforced No
  args:
    executable: powershell.exe
  loop:
    - 'Remove Shutdown and Power Buttons'
    - 'Idle RDS Session Timeout - 15 Minutes'

- name: Delete Temp Directory on target
  ansible.windows.win_file:
    path: "{{ temp_directory }}"
    state: absent