---
- name: Ensure Temp directory exists on target
  ansible.windows.win_file:
    path: "{{ temp_directory }}"
    state: directory

- name: Copy PowerShell scripts to target machine
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ temp_directory }}\\{{ item | basename }}"
  loop:
    - auto_logout_rdp_gpo.ps1
    - remove_power_buttons_gpo.ps1
    - interactive_logon_gpo.ps1

- name: Execute GPO scripts from temp directory
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File "{{ temp_directory }}\\{{ item }}"
  args:
    executable: powershell.exe
  loop:
    - remove_power_buttons_gpo.ps1
    - auto_logout_rdp_gpo.ps1
    - interactive_logon_gpo.ps1

- name: Link GPOs to domain root
  ansible.windows.win_shell: |
    New-GPLink -Name '{{ item }}' -Target '{{ domain_dn }}' -LinkEnabled Yes -Enforced No
  args:
    executable: powershell.exe
  loop:
    - 'Remove Shutdown and Power Buttons'
    - 'Idle RDS Session Timeout - 15 Minutes'
    - 'Interactive Logon Message'

- name: Delete Temp Directory on target
  ansible.windows.win_file:
    path: "{{ temp_directory }}"
    state: absent