---
- name: Master Playbook for Redhat Linux Systems
  hosts: all
  become: true
  vars_files:
    - group_vars/group_vars.yml

  tasks:
    # - name: Run Preliminaries
    #   ansible.builtin.include_tasks: preliminaries/prelims.yml

    # - name: Include Install and Configure Samba
    #   include_role:
    #     name: Samba_Install_Configure

    # - name: Include Install and Configure Httpd Web Server
    #   include_role:
    #     name: httpd
    
    # # - name: Include Clamav Configuration
    # #   include_role:
    # #     name: clamav
  
    # - name: Include Firewalld Configuration
    #   include_role:
    #     name: firewalld

    # # - name: Remove Firewalld Configuration
    # #   include_role:
    # #     name: remove_firewalld

    # - name: Include Keycloak Installation
    #   include_role:
    #     name: keycloak

    # - name: Include Zabbix Server Installation
    #   include_role:
    #     name: zabbix

    # - name: Include Section 1 RHEL9 CIS Hardening
    #   import_role:
    #     name: hardening
- name: Include RHEL 9 Hardening and Goss Auditing 
  hosts: all
  gather_facts: false
  roles:
    # - role: RHEL9-CIS-devel
    - role: RHEL9-CIS-Audit
    # - role: goss-manual
