---
- name: Set up Samba File Server on AlmaLinux
  hosts: all
  become: true
  vars_files:
    - group_vars/group_vars.yml

  tasks:
    # - name: Run Preliminaries
    #   ansible.builtin.include_tasks: preliminaries/prelims.yml

    # - name: Include Install and Configure Samba
    #   include_role:
    #     name: Samba_Install_Configure

    # - name: Include Install and Configure Httpd Web Server
    #   include_role:
    #     name: Httpd_Install_Configure
    
    # # - name: Include Clamav Configuration
    # #   include_role:
    # #     name: clamav
  
    # - name: Include Firewalld Configuration
    #   include_role:
    #     name: firewalld

    # # - name: Remove Firewalld Configuration
    # #   include_role:
    # #     name: remove_firewalld

- name: Include RHEL 9 Hardening
  hosts: all
  gather_facts: false
  roles:
    - role: RHEL9-CIS-devel
